### PR TITLE
Tests for policies

### PR DESCRIPTION
**Pull request by pau4o**
Work in progress for policy tests.

### CODE REVIEW

**Comment by theory** [comment]
Nice. I suggest adding tests, though, and docs. You might also need to make some patches to remove functionality for older versions of pgTAP; see the patches in [`compat`](/theory/pgtap/tree/master/compat) and how the [`Makefile](/theory/pgtap/blob/master/Makefile#L114) selects which patches to apply.

**Comment by pau4o** [comment]
@theory thank you for the guidance. I'll check given pointers and improve code. Tests are planned as well ;-)

**Comment by theory** [comment]
Looks great! Wonder whether it will build on older versions of Postgres; CI tests likely won't run until you submit a PR.

**Comment by pau4o** [comment]
@theory I intend to add more functions to test details related to policies (for which command is policy, for which role is policy etc.) and this is the reason that I didn't make PR in your repository.
Did you prefer to make smaller PR with only with current function?

As for patches in `compat` I didn't create them at the moment because I'm not sure that I understand correctly what is logic for patches:
- are they revert parts of code for older version
- why we have mostly identical patches in: [install-9.6.patch](https://github.com/theory/pgtap/blob/master/compat/install-9.6.patch) and [pgtap--0.97.0--0.98.0.patch](https://github.com/theory/pgtap/blob/master/compat/9.6/pgtap--0.97.0--0.98.0.patch)

It will be helpful for me to have a little bit more guidance for patches and understanding `Makefile` better.

**Comment by theory** [comment]
> Did you prefer to make smaller PR with only with current function?

No, do whatever you're comfortable with.

> * are they revert parts of code for older version

Yes, they revert code to make it compatible on older versions of Postgres. I can make them when I merge the PR, though.

> * why we have mostly identical patches in: [install-9.6.patch](
/theory/pgtap/blob/master/compat/install-9.6.patch) and [pgtap--0.97.0--0.98.0.patch](
https://github.com/theory/pgtap/blob/master/compat/9.6/pgtap--0.97.0--0.98.0.patch)

The former patches the main code file, while the latter patches the script used to upgrade an installation of v0.97.0 to v0.98.0.

**Comment by pau4o** [comment]
@theory it will be great that you make patches. Thank you.

**Pull request merged**
